// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package sileo

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "sort"

func themeAttr(t Theme) string {
	switch t {
	case ThemeDark:
		return "dark"
	case ThemeLight:
		return "light"
	case ThemeSystem:
		return "light"
	}
	return ""
}

func activePositions(items []Item, fallback Position) []Position {
	m := make(map[Position]bool)
	for _, it := range items {
		m[it.Position] = true
	}
	if _, ok := m[fallback]; !ok && fallback != "" {
		m[fallback] = true
	}
	out := make([]Position, 0, len(m))
	for _, p := range Positions {
		if m[p] {
			out = append(out, p)
		}
	}
	return out
}

func itemsAt(items []Item, pos Position) []Item {
	var out []Item
	for _, it := range items {
		if it.Position == pos {
			out = append(out, it)
		}
	}
	// Stable order: instanceId lexicographic matches insertion order roughly.
	sort.SliceStable(out, func(i, j int) bool {
		return out[i].InstanceID < out[j].InstanceID
	})
	return out
}

func Toaster(props ToasterProps, items []Item) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		theme := themeAttr(props.Theme)
		for _, pos := range activePositions(items, props.Position) {
			templ_7745c5c3_Err = Viewport(pos, itemsAt(items, pos), props.Offset, theme).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
